version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: 'dev-coinbase-ecr-repository'
    AWS_ACCOUNT_ID: '036710734874'

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing Dependencies
      - npm install
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_ACCOUNT_ID
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo $IMAGE_TAG
      - npm test
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image details file...
      - printf '{"ImageURI":"%s", "tagId":"%s" , "repositoryUri" :"%s"}' $REPOSITORY_URI:$IMAGE_TAG $IMAGE_TAG $REPOSITORY_URI > imageDetail.json
      - cat imageDetail.json
artifacts:
  files: 
      - 'image*.json'
      - 'buildspec*.yml'
      - 'coinbase-service-k8s.yaml'
      - 'service-patch.yml'
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - buildspec-green.yml
        - coinbase-service-k8s.yaml
        - service-patch.yml
    ImageArtifact:
      files:
        - imageDetail.json